### ISSUE TITLE
Hang when typing special characters with non US keyboard

### ISSUE THREAD

**Issue by srazzell** [mchakravarty/CodeEditorView#101]
I'm running into an issue where the CodeEditorView hangs if you type some special characters. I'm using a Portuguese keyboard and I can always reproduce the issue in the preview by typing "[dead keys](https://support.apple.com/guide/mac-help/enter-characters-with-accent-marks-on-mac-mh27474/mac)", such as these characters: `~` and `´` which you get from the `'` and `]` keys on US keyboards, respectively. I'm using it on macOS, haven't tested iOS. Any ideas why, or any suggestions for workarounds?

EDIT: I've narrowed it down to the `layoutManager.setRenderingAttributes` calls in `CodeStorage` running in a thread. It seems bad things happen when you call AppKit on a background thread.

MacOS: 14.1
Xcode: 15.1

**Comment by mchakravarty** [comment]
Thanks for the report. I will have a look.

**Comment by mchakravarty** [comment]
Should be fine now. Please let me know if there are still problems.

**Comment by srazzell** [comment]
Thanks for the quick fix! I don't see it hanging anymore. Really appreciate the effort.
