### ISSUE TITLE
Add SQLite language configuration

### ISSUE THREAD

**Issue by barnettben** [mchakravarty/CodeEditorView#116]
As suggested in #112 ([here](https://github.com/mchakravarty/CodeEditorView/issues/112#issuecomment-2455593664)), this ticket can be used to track progress of an SQL/SQLite language configuration.

I will hopefully have a go over the next week or so.

**Comment by barnettben** [comment]
Hi @mchakravarty and @ericzakariasson,

I've opened a draft pull request with a mostly-working implementation. I've hit a bit of a block with negative numbers, but will have another look sometime this week.

Draft PR: #117.

**Comment by mchakravarty** [comment]
@barnettben That's great — thank you!

I had a quick look and commented on the issue with negative numbers in the PR. I will try to have a closer look this week, but can't promise that as it is quite a busy week already. Otherwise, I'll have a look next week.

**Comment by barnettben** [comment]
@mchakravarty Thank you for accepting the PR. I'll close this issue now.

**Comment by mchakravarty** [comment]
Thank you for your contribution!
