### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by markusmoenig** [mchakravarty/CodeEditorView#40]
Hi,

thank you very much for this. A good code editor is urgently needed for SwiftUI! This really fills a void. Would be so cool not to have to use Ace in a WebView anymore.

Some questions:

1. Will it be possible to have sessions, i.e. when you have several source files to switch between source sessions which restores the cursor / scroll location for that session (and the messages if possible) ?
2. Will it be possible to to provide custom syntax highlighting for custom languages from the outside ? I have my own scripting language.

IMHO focus on making the core usable for a v1 and add all the options / features later ...

Thanks

**Comment by markusmoenig** [comment]
Hi,

sorry for the late reply, I switched temporarily back to Ace as I had random crashes during startup on the Monterey Beta. Have to test again with the release version.

1. I would suggest a Session struct which holds all relative internal and external data, like messages etc. everything which is session relevant. You can than bind to the current session. At least Ace does it this way. In Ace actually all functions are relevant to the current session.

2. Sounds good to me!

Again, I would focus mainly on getting a v1 of the core editor out (stability and speed). People will bombard you with feature requests but if the core is not ready the features will not matter.

Thanks for listening!

**Comment by mchakravarty** [comment]
Yes, good points, thanks!

BTW, are you using `SceneStorage`? That would be a natural place to store properties, such as the selection and scroll position.

**Comment by markusmoenig** [comment]
No, I am not using SceneStorage but if you go this way I don't see a reason why I could not implement it on my side for the editor.

btw; the crashes I had were not due to the editor, as I still, have them.

**Comment by mchakravarty** [comment]
Ok, good to know.

I will have a go at this and see what the trade offs are.

**Comment by mchakravarty** [comment]
Hi Markus,

I have added a binding to a new type `CodeEditor.EditLocation` as an additional argument to the `CodeEditor` view. It contains the current selection and scroll position. If you persist the value in the binding and restore it on application restart, you ought to get a persistent selection and scroll position.

In the [demo app](https://github.com/mchakravarty/CodeEditorDemo), I am now using this binding together with `@SceneState` to achieve making these properties of the editor persistent. But that is just one (very simple) way of using the binding, you can store its contents in any way you like (it is `RawRepresentable` serialising to a `String`).

Please let me know if this is solving your issue.

**Comment by markusmoenig** [comment]
Wow, that was quick, thanks! Did not test it in detail but it looks like it covers everything, perfect!

**Comment by mchakravarty** [comment]
Great, then I'll close this issue. Just let me know if there is anything else.
