### ISSUE TITLE
Crash in GutterView.swift

### ISSUE THREAD

**Issue by ronyfadel** [mchakravarty/CodeEditorView#46]
I'm seeing a crash when emptying all text, when accessing `message[0]`.

Worked around here:

https://github.com/mchakravarty/CodeEditorView/compare/main...ronyfadel:CodeEditorView:main

**Comment by mchakravarty** [comment]
Good catch — thanks! I will fix that.

**Comment by mj-hd** [comment]
@mchakravarty I have the same problem, has this fix been released?

**Comment by mchakravarty** [comment]
@mj-hd No, but it has been merged on the main branch (which has many more improvements by the way). Could you maybe try that?

I would like to make a release soon, so some more testing would be great!

**Comment by mj-hd** [comment]
@mchakravarty I've confirmed the bug has been fixed on my device (no crashes after updated). Thanks! I'm waiting for the next release.

**Comment by mchakravarty** [comment]
@mj-hd Thanks for the confirmation. I just released 0.11.0.
