### ISSUE TITLE
Disable word wrapping ?

### ISSUE THREAD

**Issue by livv** [mchakravarty/CodeEditorView#47]

**Comment by mchakravarty** [comment]
Do you mean having the option to disable word wrapping as part of the configuration?

**Comment by livv** [comment]
yes，could you provide this option?

**Comment by mchakravarty** [comment]
Yes, I'll have a look at what's necessary.

**Comment by mchakravarty** [comment]
Use `wrapsTextToHorizontalBounds` from `TextViewPlus`.

**Comment by mchakravarty** [comment]
Can't use `TextViewPlus`, but see also #18.

**Comment by mchakravarty** [comment]
@livv This was significantly more tricky than I thought, but it should work now.
