### ISSUE TITLE
No such module 'Rearrange'

### ISSUE THREAD

**Issue by xDragonZ** [mchakravarty/CodeEditorView#53]
Latest commit that use Rearrange package will throw this error during compile.
Try to add Rearrange to Build Phase -> Target Dependencies doesn't solve the issue.

Steps:
1) Clean Build Folder (we need to run this, then it will show Rearrange not found)
2) Build the app

![image](https://user-images.githubusercontent.com/951083/220139062-dc0971b6-cbe2-4059-bb8e-f4277cc9c0de.png)

**Comment by mchakravarty** [comment]
What project are you building? Just `CodeEditorView` on its own? (It's a SPM package; hence, the Build Phase dependencies don't matter the dependencies are in the `Package.swift` file.)

If this is in an Xcode project that does add `CodeEditorView` as an SPM dependencies, then maybe you need to re-resolve package dependencies. You can do this, e.g., via the FIle menu, see screenshot.

<img width="557" alt="image" src="https://user-images.githubusercontent.com/709989/220328108-af3d08d3-b14c-49f5-b438-815ef7d05304.png">

**Comment by xDragonZ** [comment]
Using it as SPM package (main branch, xcode 14.2) 

I have try to Resolve Package Versions, but it still having the same error. Even I manage solve it locally, the xcode cloud or CI will fail since it will throw the module not found error. 

1) Clean Build Folder
2) Compile
3) Error show up
4) Compile again then works

Is it possible that you include the Rearrage class directly in the project source code?

**Comment by mchakravarty** [comment]
Sorry, this is my fault. I forgot to add `Rearrange` to the second target in the `Package.swift` file and by chance the timing was such that this didn't break my build. This commit should fix it: https://github.com/mchakravarty/CodeEditorView/commit/ccf8091846c37bb8125b1af22526f88fd58fee4e

Please let me know if this remains a problem for you. Sorry again for the mistake.

**Comment by xDragonZ** [comment]
Yay, working great now, thank you
