### ISSUE TITLE
Unable to position the cursor accurately

### ISSUE THREAD

**Issue by xDragonZ** [mchakravarty/CodeEditorView#54]
Tested on real iphone devices and simulator. Simulator works fine with the mouse.

However in real devices, when trying to position the cursor position between semi quote text by touching the screen with hand, the cursor position appear at the wrong side.

**Comment by mchakravarty** [comment]
What do you mean by "semi quote"? Can you maybe provide an example text? (That makes it easier for me to test this.)

**Comment by xDragonZ** [comment]
Sorry, looks like it's iOS issue: https://discussions.apple.com/thread/250699056
