### ISSUE TITLE
Why are the defaultDark and defaultLight font names inconsistent?

### ISSUE THREAD

**Issue by kkk669** [mchakravarty/CodeEditorView#95]
The font name of `Theme.defaultLight` is `SFMono-Regular` but the one of `Theme.defaultDark` is `SFMono-Medium`. Why are they inconsistent?

- `Theme.defaultDark`
  - https://github.com/mchakravarty/CodeEditorView/blob/682ed1893d7addea717c4914914f9faf44abe3ff/Sources/CodeEditorView/Theme.swift#L119
- `Theme.defaultLight`
  - https://github.com/mchakravarty/CodeEditorView/blob/682ed1893d7addea717c4914914f9faf44abe3ff/Sources/CodeEditorView/Theme.swift#L136

By the way, `Theme.defaultDark` actually uses `SFMono-Regular`. It's because of the following line.

https://github.com/mchakravarty/CodeEditorView/blob/682ed1893d7addea717c4914914f9faf44abe3ff/Sources/CodeEditorView/Theme.swift#L159

`"SFMono-Medium".dropFirst("SFMono".count)` is `"-Medium"` not `"Medium"`.

**Comment by mchakravarty** [comment]
Thank you for reporting this. The intention was to use medium also for the default light theme.

**Comment by mchakravarty** [comment]
I fixed it.
