### ISSUE TITLE
Support visionOS

### ISSUE THREAD

**Issue by linhaosunny** [mchakravarty/CodeEditorView#98]
* [x] Support building on visionOS
* [x] Add a visionOS target to the demo app
* [x] Bug: text isn't shifted so that it appears to the right of the gutter.
* [x] Minimap (re)drawing doesn't work properly. Remaining issue moved to #99.

**Comment by mchakravarty** [comment]
Well according to [Swift Package Index](https://swiftpackageindex.com/mchakravarty/CodeEditorView), version 0.12.0 builds on visionOS. I am happy to keep it this way if somebody really wants to use the package on visionOS. Have you got a use for it?
